services:
  - type: web
    name: agropakar
    runtime: docker
    plan: free
    # Hapus buildCommand karena Dockerfile sudah menangani semuanya
    # Hapus startCommand karena Dockerfile (Apache) sudah berjalan otomatis
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-ap-southeast-2.pooler.supabase.com
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.qsbxvnamgelfaosgvvgp
      - key: DB_PASSWORD
        value: aKevin_200221